name: Build Folia (dev/hard-fork) Nightly - Following Paper Docs

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  # Schedule to run daily at 00:00 EEST (which is 21:00 UTC)
  schedule:
    - cron: '0 21 * * *' # Runs at 9 PM UTC daily

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest # Use a standard Linux runner

    steps:
      - name: Checkout Folia Source Code
        uses: actions/checkout@v4
        with:
          repository: 'PaperMC/Folia' # The repository to checkout
          ref: 'dev/hard-fork'       # The specific branch to checkout
          path: 'folia-src'          # Checkout into a subdirectory

      # Step Updated: Use JDK 21 as specified in the documentation
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'         # Using JDK 21 per Paper documentation
          distribution: 'temurin'    # Use Eclipse Temurin distribution
          cache: 'gradle'            # Cache Gradle dependencies

      - name: Grant Execute Permission to gradlew
        working-directory: ./folia-src # Run in the checked-out directory
        run: chmod +x gradlew

      # Step Updated: Use applyPatches as specified in the documentation
      # Note: If this fails again with ambiguity, applyAllPatches might be needed for this specific branch
      - name: Apply Patches (per Paper docs)
        working-directory: ./folia-src # Run in the checked-out directory
        run: ./gradlew applyPatches    # Using applyPatches per Paper documentation
        env:
            # Address potential Gradle daemon native access warnings (optional)
            GRADLE_OPTS: "--enable-native-access=ALL-UNNAMED"

      # Step Updated: Use createMojmapBundlerJar as specified in the documentation
      - name: Build Folia Mojmap Bundler JAR (per Paper docs)
        working-directory: ./folia-src # Run in the checked-out directory
        run: ./gradlew createMojmapBundlerJar # Using createMojmapBundlerJar per Paper documentation
        env:
            # Address potential Gradle daemon native access warnings (optional)
            GRADLE_OPTS: "--enable-native-access=ALL-UNNAMED"

      # Step Updated: Adjust path based on documentation's expected output location
      - name: Upload Folia JAR Artifact
        uses: actions/upload-artifact@v4
        with:
          # Updated artifact name slightly for clarity
          name: folia-dev-hard-fork-mojmap-jar
          # Updated path: Using the path structure from the docs (paper-server/build/libs)
          # Using wildcard *.jar as the exact filename might vary.
          path: ./folia-src/paper-server/build/libs/*.jar
          if-no-files-found: error # Fail the step if the JAR isn't found
