name: Build Folia (dev/hard-fork) Nightly

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  
  schedule:
    - cron: '0 21 * * *' # Runs at 9 PM UTC daily (00:00 EEST)
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Folia Source Code
        uses: actions/checkout@v4
        with:
          repository: 'PaperMC/Folia'
          ref: 'dev/hard-fork'
          path: 'folia-src'

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'gradle'

      - name: Grant Execute Permission to gradlew
        working-directory: ./folia-src
        run: chmod +x gradlew

      - name: Apply All Patches # <--- Renamed task for clarity
        working-directory: ./folia-src
        # Use the unambiguous task name 'applyAllPatches'
        run: ./gradlew applyAllPatches # <--- THIS IS THE CHANGED LINE
        env:
            GRADLE_OPTS: "--enable-native-access=ALL-UNNAMED"

      - name: Build Folia JAR
        working-directory: ./folia-src
        run: ./gradlew createReobfBundlerJar
        env:
            GRADLE_OPTS: "--enable-native-access=ALL-UNNAMED"

      - name: Upload Folia JAR Artifact
        uses: actions/upload-artifact@v4
        with:
          name: folia-dev-hard-fork-jar
          path: ./folia-src/build/libs/folia-bundler-*.jar
          if-no-files-found: error
